const GLOBAL = {};
GLOBAL.ENV = {};
GLOBAL.DATA_FILES = {};
GLOBAL.INDEX = {};
GLOBAL.ROUTES = {};
GLOBAL.SEND_DATA = {};

module.exports = {
  GLOBAL,
  GLOBAL_ENV: GLOBAL.ENV,
  GLOBAL_DATA_FILES: GLOBAL.DATA_FILES,
  GLOBAL_INDEX: GLOBAL.INDEX,
  GLOBAL_ROUTES: GLOBAL.ROUTES,
  GLOBAL_SEND_DATA: GLOBAL.SEND_DATA,
};
